src/Custom/CMSBundle/Form/PageType.php
<?php

namespace Custom\CMSBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PageType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('category')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Custom\CMSBundle\Entity\Page'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'custom_cmsbundle_page';
    }
}

src/Custom/CMSBundle/Controller/DefaultController.php
<?php

namespace Custom\CMSBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    public function indexAction()
    {
    	$em = $this->getDoctrine()->getManager();
    	$pages = $em->getRepository('CustomCMSBundle:Page')->findAll();
        return $this->render('CustomCMSBundle:Default:index.html.twig', array(
        	'pages'=>$pages
    	));
    }

    public function displayAction($id) {
    	$em = $this->getDoctrine()->getManager();
    	$page = $em->getRepository('CustomCMSBundle:Page')->find($id);
    	return $this->render('CustomCMSBundle:Default:display.html.twig', array(
    		'page'=>$page
		));
    }
}

src/Custom/CMSBundle/Resources/views/Default/display.html.twig
{% extends '::base.html.twig' %}

{% block body %}
	<h1>{{ page.title }}</h1>
	<h4>Category: {{ page.category.name }}</h4>
	<p>{{ page.content }}</p>
{% endblock %}

src/Custom/CMSBundle/Resources/views/Default/index.html.twig
{% extends '::base.html.twig' %}

{% block body %}
	{% for page in pages %}
		<div class="page">
			<h1>{{ page.title }}</h1>
			<p>{{ page.content|slice(0,25) }}...
				<a href="{{ path('custom_cms_page_display', {id: page.id }) }}">read more</a></p>
		</div>
	{% endfor %}
{% endblock %}